spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        subscription:
          subscribed:
            name: subscribed
          unsubscribed:
            name: unsubscribed

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    from: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    subject: Notification from App
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

messages:
  basename: messages
  notification:
    email:
      user:
        subscription: notification.email.user.subscription
        unsubscription: notification.email.user.unsubscription

logging:
  level:
    root: info

client:
  skip_event:
    header: X-Skip-Event
  user-service:
    name: user-service
    host: localhost
    port: 8080
    base-path: /api/users

server:
  port: 8084
